name: Build APK

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    # ... الخطوات الأخرى ...
    
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4   # ✅ تم التغيير إلى v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
